### PR TITLE
Create example6.append.py

### PR DESCRIPTION
**Pull request by wernight**
Example showing how to update the tree without having to sub-class.

### CODE REVIEW

**Comment by pazz** [comment]
your forgot to import subprocess.
Also, a `python example.py` fails due to the non-ascii symbol for me..

**Comment by wernight** [comment]
Thanks! Updated

**Comment by pazz** [comment]
While you're at it you could also add these examples to the docs.
I prefer the what-it-does string in the docs and not the code to be honest.

**Comment by wernight** [comment]
The doc doesn't contain code, just showing the result, which IMO explains a bit what it does.

I didn't clone so it's harder for me to change, and it seems that the doc is pretty empty, just a list of headers.

**Comment by pazz** [comment]
yea but the doc source includes the example code.
see https://urwidtrees.readthedocs.org/en/latest/examples.html
for the generated result. You can add comments (eg what it does)
between the header and the includes in this file: https://raw.githubusercontent.com/pazz/urwidtrees/master/docs/source/examples.rst

**Comment by wernight** [comment]
Can you accept the two PR and then I'll make another to update the doc and more docstring to the doc.

**Comment by pazz** [comment]
I'd rather you finish your changes, squash them into small commits that
actually do what you want and update the PR.
I'm happy to push it once its ready.
The thing i just that I really don't want to have patchsets where
a later commit undoes what an earlier one introduced. This is terrible to
review.

Quoting Werner Beroux (2015-03-12 16:59:01)

**Comment by wernight** [comment]
Droppping this PR, merged into my patch-1 PR.

**Pull request closed without merging**
