### PR TITLE
Fix python3 import errors

### PR DESCRIPTION
**Pull request by rndusr**

### CODE REVIEW

**Comment by rndusr** [comment]
I also get the following import error with python2.7:

      File "urwidtrees/widgets.py", line 49, in TreeListWalker
        @lru_cache()
    TypeError: 'module' object is not callable

`from cachetools.lru import lru_cache` in __init__.py fixes this for me, but I don't know if there are other implementations and which one you're using, so I didn't include that in this pull request.

**Comment by pazz** [comment]
Hi! Thanks for taking the time to send this in.

Quoting rndusr (2015-02-06 14:34:55)
> I also get the following import error with python2.7:
> 
>   File "urwidtrees/widgets.py", line 49, in TreeListWalker
>     @lru_cache()
> TypeError: 'module' object is not callable
> 
> from cachetools.lru import lru_cache in init.py fixes this for me, but I don't
> know if there are other implementations and which one you're using, so I didn't
> include that in this pull request.


As mentioned in the first two lines of the local version of lru_cache
(urwidtrees/lru_cache.py), this is a backport i just got of the internet.
It is true that this is part of the sdtlib in python 3.

Now I also get the error trace you mention, when I do 

  ./setup.py install --user

But only on your new branch, not on the master branch.
So I'll refrain from pushing this here until we've figured out what's wrong..

**Comment by rndusr** [comment]
I tried importing lru_cache from main in widgets.py, imported it from
. instead, which resulted in "lru_cache" being a module, explaining the
TypeError.

That's fixed now and everything works for me with python2 and 3.

But I still don't understand why lru_cache is imported in __init__.py in the
first place. It's only used in widgets.py, which always imports it from the
backport in urwidtrees/lru_cache.py both in python2 and 3. The lru_cache from
functools is never used, isn't it?

Also, there's a python2 implementation in a module called cachetools. Maybe it
would be better using that?
https://github.com/tkem/cachetools/

**Comment by pazz** [comment]
Quoting rndusr (2015-02-08 13:30:51)
> I tried importing lru_cache from main in widgets.py, imported it from
> . instead, which resulted in "lru_cache" being a module, explaining the
> TypeError.
> 
> That's fixed now and everything works for me with python2 and 3.

Excellent! thanks.

> But I still don't understand why lru_cache is imported in __init__.py in the
> first place. It's only used in widgets.py, which always imports it from the
> backport in urwidtrees/lru_cache.py both in python2 and 3. 

You are right. it should only be imported where it's used.

> The lru_cache from functools is never used, isn't it?
> 
> Also, there's a python2 implementation in a module called cachetools. Maybe it
> would be better using that?
> https://github.com/tkem/cachetools/

I honestly did not spend too much time researching this.
I wanted (and still want) a backport that works in py2 and that behaves exactly
like the one in py3.2's standard lib.
Moreover, I want to avoid unnecessary dependencies, which is why
there is a local copy of lru_cache.py included.
Is there a good case for this 'cachetools' dependency to be made
over the current solution?

**Comment by rndusr** [comment]
> Moreover, I want to avoid unnecessary dependencies, which is why
> there is a local copy of lru_cache.py included.
> Is there a good case for this 'cachetools' dependency to be made
> over the current solution?

I don't know, I just tested a few of the examples with cachetools and it seems
to work. The cachetools implementation also takes the same arguments as the
one in urwidtrees.

In general, I think it's better to use existing implementations to reduce the
work load of maintenance, bug hunting, optimizations, etc. But I see your
point, and we're not talking about something highly complex like a crypto
module.

**Comment by pazz** [comment]
sure, i agree. But really: I want to avoid an extra dependency here.
This whole project is a by-product of another project I'm maintaining, and it makes
life hard for package maintainers if we add a dep for somthing that isnt already packaged
(e.g. on debian).

**Comment by rndusr** [comment]
Yes, I fully understand and I reverted the last commit that uses cachetools.

BTW, are there any plans to integrate urwidtree in urwid? I haven't had a good
look yet, but it seems superior to the tree implementation in urwid. (Hence my
interest in it.)

**Comment by pazz** [comment]
thanks. There are sort of. I would like to merge this into upstream urwid.
but this means I'd have so spend some time cleaning it up and write a pull request..

**Pull request merged**
